model:
    model_type: GyroGr
    channels: 8
    subspace_dim: 10
    architecture: [[93,93]] #[[93,93]], [[93,93],[47,47]]
    is_pooling: True # False,True
    is_final_pooling: True

BN_param:
    is_bn: False
    bn_type: GyroBNGr #GyroBNGr,RBNGr,ManifoldNormGr

optimizer:
    optimizer_mode: SGD #SGD,ADAM,AMSGRAD, Adadelta for Gyro
    lr: 5e-2 #5e-2, and 1 for Adadelta
    weight_decay: 0.
